name: codonshuffle_env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - pandas
  - statsmodels
  - patsy
  - biopython
  - plotnine
  - viennarna